{
  imports = [
    ./packages.nix
    ./broot.nix
    ./git.nix
    ./vscode.nix
    ./fcitx5.nix
    ./shell.nix
    ./obs.nix
    ./zathura.nix
    ./direnv.nix
    ./eza.nix
    ./yazi.nix
    ./ssh.nix
    ./fzf.nix
    ./zed.nix
    ./nvim.nix
    ./ghostty.nix
    ./satty.nix
    ./zellij.nix
    ./desktopEntries.nix
    ./syncthing.nix
  ];
}
