# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "uas" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/9a44ff31-7d2c-40ff-b062-2eb985fc8723";
      fsType = "btrfs";
      options = [ "subvol=@" "compress=zstd"];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/9a44ff31-7d2c-40ff-b062-2eb985fc8723";
      fsType = "btrfs";
      options = [ "subvol=@home"  "compress=zstd"];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/9a44ff31-7d2c-40ff-b062-2eb985fc8723";
      fsType = "btrfs";
      options = [ "subvol=@nix"   "compress=zstd" "noatime"];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/A226-FBC7";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/7abf017f-cccb-449e-9144-ac2f79b548b3"; options = ["noatime"];
 }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
